// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class Medications extends Table with TableInfo<Medications, MedicationsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  Medications(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> form = GeneratedColumn<String>(
    'form',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<double> doseAmount = GeneratedColumn<double>(
    'dose_amount',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> doseUnit = GeneratedColumn<String>(
    'dose_unit',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> typeKind = GeneratedColumn<String>(
    'type_kind',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> frequency = GeneratedColumn<String>(
    'frequency',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> startDate = GeneratedColumn<int>(
    'start_date',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> durationDays = GeneratedColumn<int>(
    'duration_days',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> pauseDays = GeneratedColumn<int>(
    'pause_days',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> stockRemaining = GeneratedColumn<int>(
    'stock_remaining',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> stockTotal = GeneratedColumn<int>(
    'stock_total',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> stockWarnAt = GeneratedColumn<int>(
    'stock_warn_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> notes = GeneratedColumn<String>(
    'notes',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    name,
    form,
    doseAmount,
    doseUnit,
    typeKind,
    frequency,
    startDate,
    durationDays,
    pauseDays,
    stockRemaining,
    stockTotal,
    stockWarnAt,
    notes,
    createdAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'medications';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  MedicationsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return MedicationsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      name: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}name'],
      )!,
      form: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}form'],
      )!,
      doseAmount: attachedDatabase.typeMapping.read(
        DriftSqlType.double,
        data['${effectivePrefix}dose_amount'],
      ),
      doseUnit: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}dose_unit'],
      ),
      typeKind: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}type_kind'],
      )!,
      frequency: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}frequency'],
      )!,
      startDate: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}start_date'],
      )!,
      durationDays: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}duration_days'],
      ),
      pauseDays: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}pause_days'],
      ),
      stockRemaining: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}stock_remaining'],
      ),
      stockTotal: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}stock_total'],
      ),
      stockWarnAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}stock_warn_at'],
      ),
      notes: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}notes'],
      ),
      createdAt: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at'],
      )!,
    );
  }

  @override
  Medications createAlias(String alias) {
    return Medications(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class MedicationsData extends DataClass implements Insertable<MedicationsData> {
  final String id;
  final String name;
  final String form;
  final double? doseAmount;
  final String? doseUnit;
  final String typeKind;
  final String frequency;
  final int startDate;
  final int? durationDays;
  final int? pauseDays;
  final int? stockRemaining;
  final int? stockTotal;
  final int? stockWarnAt;
  final String? notes;
  final int createdAt;
  const MedicationsData({
    required this.id,
    required this.name,
    required this.form,
    this.doseAmount,
    this.doseUnit,
    required this.typeKind,
    required this.frequency,
    required this.startDate,
    this.durationDays,
    this.pauseDays,
    this.stockRemaining,
    this.stockTotal,
    this.stockWarnAt,
    this.notes,
    required this.createdAt,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['name'] = Variable<String>(name);
    map['form'] = Variable<String>(form);
    if (!nullToAbsent || doseAmount != null) {
      map['dose_amount'] = Variable<double>(doseAmount);
    }
    if (!nullToAbsent || doseUnit != null) {
      map['dose_unit'] = Variable<String>(doseUnit);
    }
    map['type_kind'] = Variable<String>(typeKind);
    map['frequency'] = Variable<String>(frequency);
    map['start_date'] = Variable<int>(startDate);
    if (!nullToAbsent || durationDays != null) {
      map['duration_days'] = Variable<int>(durationDays);
    }
    if (!nullToAbsent || pauseDays != null) {
      map['pause_days'] = Variable<int>(pauseDays);
    }
    if (!nullToAbsent || stockRemaining != null) {
      map['stock_remaining'] = Variable<int>(stockRemaining);
    }
    if (!nullToAbsent || stockTotal != null) {
      map['stock_total'] = Variable<int>(stockTotal);
    }
    if (!nullToAbsent || stockWarnAt != null) {
      map['stock_warn_at'] = Variable<int>(stockWarnAt);
    }
    if (!nullToAbsent || notes != null) {
      map['notes'] = Variable<String>(notes);
    }
    map['created_at'] = Variable<int>(createdAt);
    return map;
  }

  MedicationsCompanion toCompanion(bool nullToAbsent) {
    return MedicationsCompanion(
      id: Value(id),
      name: Value(name),
      form: Value(form),
      doseAmount: doseAmount == null && nullToAbsent
          ? const Value.absent()
          : Value(doseAmount),
      doseUnit: doseUnit == null && nullToAbsent
          ? const Value.absent()
          : Value(doseUnit),
      typeKind: Value(typeKind),
      frequency: Value(frequency),
      startDate: Value(startDate),
      durationDays: durationDays == null && nullToAbsent
          ? const Value.absent()
          : Value(durationDays),
      pauseDays: pauseDays == null && nullToAbsent
          ? const Value.absent()
          : Value(pauseDays),
      stockRemaining: stockRemaining == null && nullToAbsent
          ? const Value.absent()
          : Value(stockRemaining),
      stockTotal: stockTotal == null && nullToAbsent
          ? const Value.absent()
          : Value(stockTotal),
      stockWarnAt: stockWarnAt == null && nullToAbsent
          ? const Value.absent()
          : Value(stockWarnAt),
      notes: notes == null && nullToAbsent
          ? const Value.absent()
          : Value(notes),
      createdAt: Value(createdAt),
    );
  }

  factory MedicationsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return MedicationsData(
      id: serializer.fromJson<String>(json['id']),
      name: serializer.fromJson<String>(json['name']),
      form: serializer.fromJson<String>(json['form']),
      doseAmount: serializer.fromJson<double?>(json['doseAmount']),
      doseUnit: serializer.fromJson<String?>(json['doseUnit']),
      typeKind: serializer.fromJson<String>(json['typeKind']),
      frequency: serializer.fromJson<String>(json['frequency']),
      startDate: serializer.fromJson<int>(json['startDate']),
      durationDays: serializer.fromJson<int?>(json['durationDays']),
      pauseDays: serializer.fromJson<int?>(json['pauseDays']),
      stockRemaining: serializer.fromJson<int?>(json['stockRemaining']),
      stockTotal: serializer.fromJson<int?>(json['stockTotal']),
      stockWarnAt: serializer.fromJson<int?>(json['stockWarnAt']),
      notes: serializer.fromJson<String?>(json['notes']),
      createdAt: serializer.fromJson<int>(json['createdAt']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'name': serializer.toJson<String>(name),
      'form': serializer.toJson<String>(form),
      'doseAmount': serializer.toJson<double?>(doseAmount),
      'doseUnit': serializer.toJson<String?>(doseUnit),
      'typeKind': serializer.toJson<String>(typeKind),
      'frequency': serializer.toJson<String>(frequency),
      'startDate': serializer.toJson<int>(startDate),
      'durationDays': serializer.toJson<int?>(durationDays),
      'pauseDays': serializer.toJson<int?>(pauseDays),
      'stockRemaining': serializer.toJson<int?>(stockRemaining),
      'stockTotal': serializer.toJson<int?>(stockTotal),
      'stockWarnAt': serializer.toJson<int?>(stockWarnAt),
      'notes': serializer.toJson<String?>(notes),
      'createdAt': serializer.toJson<int>(createdAt),
    };
  }

  MedicationsData copyWith({
    String? id,
    String? name,
    String? form,
    Value<double?> doseAmount = const Value.absent(),
    Value<String?> doseUnit = const Value.absent(),
    String? typeKind,
    String? frequency,
    int? startDate,
    Value<int?> durationDays = const Value.absent(),
    Value<int?> pauseDays = const Value.absent(),
    Value<int?> stockRemaining = const Value.absent(),
    Value<int?> stockTotal = const Value.absent(),
    Value<int?> stockWarnAt = const Value.absent(),
    Value<String?> notes = const Value.absent(),
    int? createdAt,
  }) => MedicationsData(
    id: id ?? this.id,
    name: name ?? this.name,
    form: form ?? this.form,
    doseAmount: doseAmount.present ? doseAmount.value : this.doseAmount,
    doseUnit: doseUnit.present ? doseUnit.value : this.doseUnit,
    typeKind: typeKind ?? this.typeKind,
    frequency: frequency ?? this.frequency,
    startDate: startDate ?? this.startDate,
    durationDays: durationDays.present ? durationDays.value : this.durationDays,
    pauseDays: pauseDays.present ? pauseDays.value : this.pauseDays,
    stockRemaining: stockRemaining.present
        ? stockRemaining.value
        : this.stockRemaining,
    stockTotal: stockTotal.present ? stockTotal.value : this.stockTotal,
    stockWarnAt: stockWarnAt.present ? stockWarnAt.value : this.stockWarnAt,
    notes: notes.present ? notes.value : this.notes,
    createdAt: createdAt ?? this.createdAt,
  );
  MedicationsData copyWithCompanion(MedicationsCompanion data) {
    return MedicationsData(
      id: data.id.present ? data.id.value : this.id,
      name: data.name.present ? data.name.value : this.name,
      form: data.form.present ? data.form.value : this.form,
      doseAmount: data.doseAmount.present
          ? data.doseAmount.value
          : this.doseAmount,
      doseUnit: data.doseUnit.present ? data.doseUnit.value : this.doseUnit,
      typeKind: data.typeKind.present ? data.typeKind.value : this.typeKind,
      frequency: data.frequency.present ? data.frequency.value : this.frequency,
      startDate: data.startDate.present ? data.startDate.value : this.startDate,
      durationDays: data.durationDays.present
          ? data.durationDays.value
          : this.durationDays,
      pauseDays: data.pauseDays.present ? data.pauseDays.value : this.pauseDays,
      stockRemaining: data.stockRemaining.present
          ? data.stockRemaining.value
          : this.stockRemaining,
      stockTotal: data.stockTotal.present
          ? data.stockTotal.value
          : this.stockTotal,
      stockWarnAt: data.stockWarnAt.present
          ? data.stockWarnAt.value
          : this.stockWarnAt,
      notes: data.notes.present ? data.notes.value : this.notes,
      createdAt: data.createdAt.present ? data.createdAt.value : this.createdAt,
    );
  }

  @override
  String toString() {
    return (StringBuffer('MedicationsData(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('form: $form, ')
          ..write('doseAmount: $doseAmount, ')
          ..write('doseUnit: $doseUnit, ')
          ..write('typeKind: $typeKind, ')
          ..write('frequency: $frequency, ')
          ..write('startDate: $startDate, ')
          ..write('durationDays: $durationDays, ')
          ..write('pauseDays: $pauseDays, ')
          ..write('stockRemaining: $stockRemaining, ')
          ..write('stockTotal: $stockTotal, ')
          ..write('stockWarnAt: $stockWarnAt, ')
          ..write('notes: $notes, ')
          ..write('createdAt: $createdAt')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    name,
    form,
    doseAmount,
    doseUnit,
    typeKind,
    frequency,
    startDate,
    durationDays,
    pauseDays,
    stockRemaining,
    stockTotal,
    stockWarnAt,
    notes,
    createdAt,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is MedicationsData &&
          other.id == this.id &&
          other.name == this.name &&
          other.form == this.form &&
          other.doseAmount == this.doseAmount &&
          other.doseUnit == this.doseUnit &&
          other.typeKind == this.typeKind &&
          other.frequency == this.frequency &&
          other.startDate == this.startDate &&
          other.durationDays == this.durationDays &&
          other.pauseDays == this.pauseDays &&
          other.stockRemaining == this.stockRemaining &&
          other.stockTotal == this.stockTotal &&
          other.stockWarnAt == this.stockWarnAt &&
          other.notes == this.notes &&
          other.createdAt == this.createdAt);
}

class MedicationsCompanion extends UpdateCompanion<MedicationsData> {
  final Value<String> id;
  final Value<String> name;
  final Value<String> form;
  final Value<double?> doseAmount;
  final Value<String?> doseUnit;
  final Value<String> typeKind;
  final Value<String> frequency;
  final Value<int> startDate;
  final Value<int?> durationDays;
  final Value<int?> pauseDays;
  final Value<int?> stockRemaining;
  final Value<int?> stockTotal;
  final Value<int?> stockWarnAt;
  final Value<String?> notes;
  final Value<int> createdAt;
  final Value<int> rowid;
  const MedicationsCompanion({
    this.id = const Value.absent(),
    this.name = const Value.absent(),
    this.form = const Value.absent(),
    this.doseAmount = const Value.absent(),
    this.doseUnit = const Value.absent(),
    this.typeKind = const Value.absent(),
    this.frequency = const Value.absent(),
    this.startDate = const Value.absent(),
    this.durationDays = const Value.absent(),
    this.pauseDays = const Value.absent(),
    this.stockRemaining = const Value.absent(),
    this.stockTotal = const Value.absent(),
    this.stockWarnAt = const Value.absent(),
    this.notes = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  MedicationsCompanion.insert({
    required String id,
    required String name,
    required String form,
    this.doseAmount = const Value.absent(),
    this.doseUnit = const Value.absent(),
    required String typeKind,
    required String frequency,
    required int startDate,
    this.durationDays = const Value.absent(),
    this.pauseDays = const Value.absent(),
    this.stockRemaining = const Value.absent(),
    this.stockTotal = const Value.absent(),
    this.stockWarnAt = const Value.absent(),
    this.notes = const Value.absent(),
    required int createdAt,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       name = Value(name),
       form = Value(form),
       typeKind = Value(typeKind),
       frequency = Value(frequency),
       startDate = Value(startDate),
       createdAt = Value(createdAt);
  static Insertable<MedicationsData> custom({
    Expression<String>? id,
    Expression<String>? name,
    Expression<String>? form,
    Expression<double>? doseAmount,
    Expression<String>? doseUnit,
    Expression<String>? typeKind,
    Expression<String>? frequency,
    Expression<int>? startDate,
    Expression<int>? durationDays,
    Expression<int>? pauseDays,
    Expression<int>? stockRemaining,
    Expression<int>? stockTotal,
    Expression<int>? stockWarnAt,
    Expression<String>? notes,
    Expression<int>? createdAt,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (name != null) 'name': name,
      if (form != null) 'form': form,
      if (doseAmount != null) 'dose_amount': doseAmount,
      if (doseUnit != null) 'dose_unit': doseUnit,
      if (typeKind != null) 'type_kind': typeKind,
      if (frequency != null) 'frequency': frequency,
      if (startDate != null) 'start_date': startDate,
      if (durationDays != null) 'duration_days': durationDays,
      if (pauseDays != null) 'pause_days': pauseDays,
      if (stockRemaining != null) 'stock_remaining': stockRemaining,
      if (stockTotal != null) 'stock_total': stockTotal,
      if (stockWarnAt != null) 'stock_warn_at': stockWarnAt,
      if (notes != null) 'notes': notes,
      if (createdAt != null) 'created_at': createdAt,
      if (rowid != null) 'rowid': rowid,
    });
  }

  MedicationsCompanion copyWith({
    Value<String>? id,
    Value<String>? name,
    Value<String>? form,
    Value<double?>? doseAmount,
    Value<String?>? doseUnit,
    Value<String>? typeKind,
    Value<String>? frequency,
    Value<int>? startDate,
    Value<int?>? durationDays,
    Value<int?>? pauseDays,
    Value<int?>? stockRemaining,
    Value<int?>? stockTotal,
    Value<int?>? stockWarnAt,
    Value<String?>? notes,
    Value<int>? createdAt,
    Value<int>? rowid,
  }) {
    return MedicationsCompanion(
      id: id ?? this.id,
      name: name ?? this.name,
      form: form ?? this.form,
      doseAmount: doseAmount ?? this.doseAmount,
      doseUnit: doseUnit ?? this.doseUnit,
      typeKind: typeKind ?? this.typeKind,
      frequency: frequency ?? this.frequency,
      startDate: startDate ?? this.startDate,
      durationDays: durationDays ?? this.durationDays,
      pauseDays: pauseDays ?? this.pauseDays,
      stockRemaining: stockRemaining ?? this.stockRemaining,
      stockTotal: stockTotal ?? this.stockTotal,
      stockWarnAt: stockWarnAt ?? this.stockWarnAt,
      notes: notes ?? this.notes,
      createdAt: createdAt ?? this.createdAt,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (name.present) {
      map['name'] = Variable<String>(name.value);
    }
    if (form.present) {
      map['form'] = Variable<String>(form.value);
    }
    if (doseAmount.present) {
      map['dose_amount'] = Variable<double>(doseAmount.value);
    }
    if (doseUnit.present) {
      map['dose_unit'] = Variable<String>(doseUnit.value);
    }
    if (typeKind.present) {
      map['type_kind'] = Variable<String>(typeKind.value);
    }
    if (frequency.present) {
      map['frequency'] = Variable<String>(frequency.value);
    }
    if (startDate.present) {
      map['start_date'] = Variable<int>(startDate.value);
    }
    if (durationDays.present) {
      map['duration_days'] = Variable<int>(durationDays.value);
    }
    if (pauseDays.present) {
      map['pause_days'] = Variable<int>(pauseDays.value);
    }
    if (stockRemaining.present) {
      map['stock_remaining'] = Variable<int>(stockRemaining.value);
    }
    if (stockTotal.present) {
      map['stock_total'] = Variable<int>(stockTotal.value);
    }
    if (stockWarnAt.present) {
      map['stock_warn_at'] = Variable<int>(stockWarnAt.value);
    }
    if (notes.present) {
      map['notes'] = Variable<String>(notes.value);
    }
    if (createdAt.present) {
      map['created_at'] = Variable<int>(createdAt.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('MedicationsCompanion(')
          ..write('id: $id, ')
          ..write('name: $name, ')
          ..write('form: $form, ')
          ..write('doseAmount: $doseAmount, ')
          ..write('doseUnit: $doseUnit, ')
          ..write('typeKind: $typeKind, ')
          ..write('frequency: $frequency, ')
          ..write('startDate: $startDate, ')
          ..write('durationDays: $durationDays, ')
          ..write('pauseDays: $pauseDays, ')
          ..write('stockRemaining: $stockRemaining, ')
          ..write('stockTotal: $stockTotal, ')
          ..write('stockWarnAt: $stockWarnAt, ')
          ..write('notes: $notes, ')
          ..write('createdAt: $createdAt, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class TimeSlots extends Table with TableInfo<TimeSlots, TimeSlotsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TimeSlots(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> medicationId = GeneratedColumn<String>(
    'medication_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES medications(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<int> minuteOfDay = GeneratedColumn<int>(
    'minute_of_day',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<double> doseAmount = GeneratedColumn<double>(
    'dose_amount',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> doseUnit = GeneratedColumn<String>(
    'dose_unit',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    medicationId,
    minuteOfDay,
    doseAmount,
    doseUnit,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'time_slots';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  TimeSlotsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TimeSlotsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      medicationId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}medication_id'],
      )!,
      minuteOfDay: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}minute_of_day'],
      )!,
      doseAmount: attachedDatabase.typeMapping.read(
        DriftSqlType.double,
        data['${effectivePrefix}dose_amount'],
      ),
      doseUnit: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}dose_unit'],
      ),
    );
  }

  @override
  TimeSlots createAlias(String alias) {
    return TimeSlots(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class TimeSlotsData extends DataClass implements Insertable<TimeSlotsData> {
  final String id;
  final String medicationId;
  final int minuteOfDay;
  final double? doseAmount;
  final String? doseUnit;
  const TimeSlotsData({
    required this.id,
    required this.medicationId,
    required this.minuteOfDay,
    this.doseAmount,
    this.doseUnit,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['medication_id'] = Variable<String>(medicationId);
    map['minute_of_day'] = Variable<int>(minuteOfDay);
    if (!nullToAbsent || doseAmount != null) {
      map['dose_amount'] = Variable<double>(doseAmount);
    }
    if (!nullToAbsent || doseUnit != null) {
      map['dose_unit'] = Variable<String>(doseUnit);
    }
    return map;
  }

  TimeSlotsCompanion toCompanion(bool nullToAbsent) {
    return TimeSlotsCompanion(
      id: Value(id),
      medicationId: Value(medicationId),
      minuteOfDay: Value(minuteOfDay),
      doseAmount: doseAmount == null && nullToAbsent
          ? const Value.absent()
          : Value(doseAmount),
      doseUnit: doseUnit == null && nullToAbsent
          ? const Value.absent()
          : Value(doseUnit),
    );
  }

  factory TimeSlotsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TimeSlotsData(
      id: serializer.fromJson<String>(json['id']),
      medicationId: serializer.fromJson<String>(json['medicationId']),
      minuteOfDay: serializer.fromJson<int>(json['minuteOfDay']),
      doseAmount: serializer.fromJson<double?>(json['doseAmount']),
      doseUnit: serializer.fromJson<String?>(json['doseUnit']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'medicationId': serializer.toJson<String>(medicationId),
      'minuteOfDay': serializer.toJson<int>(minuteOfDay),
      'doseAmount': serializer.toJson<double?>(doseAmount),
      'doseUnit': serializer.toJson<String?>(doseUnit),
    };
  }

  TimeSlotsData copyWith({
    String? id,
    String? medicationId,
    int? minuteOfDay,
    Value<double?> doseAmount = const Value.absent(),
    Value<String?> doseUnit = const Value.absent(),
  }) => TimeSlotsData(
    id: id ?? this.id,
    medicationId: medicationId ?? this.medicationId,
    minuteOfDay: minuteOfDay ?? this.minuteOfDay,
    doseAmount: doseAmount.present ? doseAmount.value : this.doseAmount,
    doseUnit: doseUnit.present ? doseUnit.value : this.doseUnit,
  );
  TimeSlotsData copyWithCompanion(TimeSlotsCompanion data) {
    return TimeSlotsData(
      id: data.id.present ? data.id.value : this.id,
      medicationId: data.medicationId.present
          ? data.medicationId.value
          : this.medicationId,
      minuteOfDay: data.minuteOfDay.present
          ? data.minuteOfDay.value
          : this.minuteOfDay,
      doseAmount: data.doseAmount.present
          ? data.doseAmount.value
          : this.doseAmount,
      doseUnit: data.doseUnit.present ? data.doseUnit.value : this.doseUnit,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TimeSlotsData(')
          ..write('id: $id, ')
          ..write('medicationId: $medicationId, ')
          ..write('minuteOfDay: $minuteOfDay, ')
          ..write('doseAmount: $doseAmount, ')
          ..write('doseUnit: $doseUnit')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode =>
      Object.hash(id, medicationId, minuteOfDay, doseAmount, doseUnit);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TimeSlotsData &&
          other.id == this.id &&
          other.medicationId == this.medicationId &&
          other.minuteOfDay == this.minuteOfDay &&
          other.doseAmount == this.doseAmount &&
          other.doseUnit == this.doseUnit);
}

class TimeSlotsCompanion extends UpdateCompanion<TimeSlotsData> {
  final Value<String> id;
  final Value<String> medicationId;
  final Value<int> minuteOfDay;
  final Value<double?> doseAmount;
  final Value<String?> doseUnit;
  final Value<int> rowid;
  const TimeSlotsCompanion({
    this.id = const Value.absent(),
    this.medicationId = const Value.absent(),
    this.minuteOfDay = const Value.absent(),
    this.doseAmount = const Value.absent(),
    this.doseUnit = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TimeSlotsCompanion.insert({
    required String id,
    required String medicationId,
    required int minuteOfDay,
    this.doseAmount = const Value.absent(),
    this.doseUnit = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       medicationId = Value(medicationId),
       minuteOfDay = Value(minuteOfDay);
  static Insertable<TimeSlotsData> custom({
    Expression<String>? id,
    Expression<String>? medicationId,
    Expression<int>? minuteOfDay,
    Expression<double>? doseAmount,
    Expression<String>? doseUnit,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (medicationId != null) 'medication_id': medicationId,
      if (minuteOfDay != null) 'minute_of_day': minuteOfDay,
      if (doseAmount != null) 'dose_amount': doseAmount,
      if (doseUnit != null) 'dose_unit': doseUnit,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TimeSlotsCompanion copyWith({
    Value<String>? id,
    Value<String>? medicationId,
    Value<int>? minuteOfDay,
    Value<double?>? doseAmount,
    Value<String?>? doseUnit,
    Value<int>? rowid,
  }) {
    return TimeSlotsCompanion(
      id: id ?? this.id,
      medicationId: medicationId ?? this.medicationId,
      minuteOfDay: minuteOfDay ?? this.minuteOfDay,
      doseAmount: doseAmount ?? this.doseAmount,
      doseUnit: doseUnit ?? this.doseUnit,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (medicationId.present) {
      map['medication_id'] = Variable<String>(medicationId.value);
    }
    if (minuteOfDay.present) {
      map['minute_of_day'] = Variable<int>(minuteOfDay.value);
    }
    if (doseAmount.present) {
      map['dose_amount'] = Variable<double>(doseAmount.value);
    }
    if (doseUnit.present) {
      map['dose_unit'] = Variable<String>(doseUnit.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TimeSlotsCompanion(')
          ..write('id: $id, ')
          ..write('medicationId: $medicationId, ')
          ..write('minuteOfDay: $minuteOfDay, ')
          ..write('doseAmount: $doseAmount, ')
          ..write('doseUnit: $doseUnit, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV1 extends GeneratedDatabase {
  DatabaseAtV1(QueryExecutor e) : super(e);
  late final Medications medications = Medications(this);
  late final TimeSlots timeSlots = TimeSlots(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [medications, timeSlots];
  @override
  StreamQueryUpdateRules get streamUpdateRules => const StreamQueryUpdateRules([
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        'medications',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('time_slots', kind: UpdateKind.delete)],
    ),
  ]);
  @override
  int get schemaVersion => 1;
}
