/// A single medication dose: an [amount] paired with its [DoseUnit].
///
/// Pure Dart value object of the medication domain model — no Flutter, drift,
/// or uuid imports (constitution §2.1). See [Dosage].
library;

import 'package:freezed_annotation/freezed_annotation.dart';

import 'dose_unit.dart';

part 'dosage.freezed.dart';

/// The quantity of medication taken in one dose.
///
/// Combines a numeric [amount] with the [unit] it is measured in (e.g.
/// `2 tablet`, `5 ml`). Equality and `hashCode` are generated by freezed.
@freezed
abstract class Dosage with _$Dosage {
  /// Creates a [Dosage] of [amount] measured in [unit].
  const factory Dosage({
    /// The numeric quantity of the dose (e.g. `2` for two tablets, `5` for 5 ml).
    required double amount,

    /// The unit [amount] is measured in.
    required DoseUnit unit,
  }) = _Dosage;
}
