/// A single scheduled medication intake occurrence: its identity, the
/// medication and time slot it belongs to, when it was due, and its current
/// lifecycle state.
///
/// Pure Dart entity of the medication domain model — no Flutter, drift, or
/// uuid imports (constitution §2.1). See [Intake].
library;

import 'package:freezed_annotation/freezed_annotation.dart';

import '../value_objects/intake_id.dart';
import '../value_objects/medication_id.dart';
import '../value_objects/time_slot_id.dart';
import 'intake_status.dart';

part 'intake.freezed.dart';

/// One occurrence of a medication being due — the record that moves through
/// the intake state machine (constitution §5.2).
///
/// Ties a scheduled occurrence to its owning [MedicationId] and the originating
/// schedule [TimeSlotId], records when it was due and (if acted upon) when it
/// was confirmed, and carries its current [IntakeStatus]. Equality and
/// `hashCode` are generated by freezed.
@freezed
abstract class Intake with _$Intake {
  /// Creates an [Intake] occurrence.
  const factory Intake({
    /// Stable, typed identifier for this intake.
    required IntakeId id,

    /// The medication this intake is an occurrence of.
    required MedicationId medicationId,

    /// The schedule time slot that generated this occurrence.
    required TimeSlotId slotId,

    /// When this intake was due, in **UTC** (constitution §"All timestamps in
    /// UTC, displayed in local").
    required DateTime scheduledAt,

    /// When the user confirmed the intake, in **UTC**. `null` while the intake
    /// has not been confirmed (e.g. pending or skipped).
    DateTime? confirmedAt,

    /// Current lifecycle state of this intake.
    required IntakeStatus status,

    /// Free-form user notes for this occurrence. `null` when none were entered.
    String? notes,
  }) = _Intake;
}
