/// The aggregate root of the medication domain model: a single medication the
/// user is tracking, with its form, temporal type, intake schedule, optional
/// dosing/stock metadata, and creation timestamp.
///
/// Pure Dart aggregate of the medication domain model — no Flutter, drift, or
/// uuid imports (constitution §2.1). See [Medication].
library;

import 'package:freezed_annotation/freezed_annotation.dart';

import '../value_objects/medication_id.dart';
import 'dosage.dart';
import 'medication_form.dart';
import 'medication_type.dart';
import 'pack_stock.dart';
import 'schedule.dart';

part 'medication.freezed.dart';

/// A medication tracked by the user — the aggregate root tying together the
/// medication's identity, presentation, temporal pattern, and intake plan.
///
/// Composes the value objects and sibling entities of the medication domain:
/// the typed [MedicationId], the physical [MedicationForm], the temporal
/// [MedicationType] (continuous vs course), and the recurring [Schedule].
/// [dosePerIntake], [stock], and [notes] are optional metadata. Equality and
/// `hashCode` are generated by freezed.
@freezed
abstract class Medication with _$Medication {
  /// Creates a [Medication] aggregate.
  const factory Medication({
    /// Stable, typed identifier for this medication.
    required MedicationId id,

    /// User-facing display name of the medication.
    required String name,

    /// Physical form the medication is taken in (tablet, syrup, …).
    required MedicationForm form,

    /// Temporal pattern of intake: continuous or a bounded/cyclic course.
    required MedicationType type,

    /// The recurring intake plan (frequency + time slots).
    required Schedule schedule,

    /// Default dose taken at each occurrence. `null` when no default dose is
    /// recorded (individual [TimeSlot]s may still carry per-slot overrides).
    Dosage? dosePerIntake,

    /// On-hand inventory tracking. `null` when stock is not tracked for this
    /// medication.
    PackStock? stock,

    /// Free-form user notes. `null` when none were entered.
    String? notes,

    /// Timestamp at which this medication record was created.
    required DateTime createdAt,
  }) = _Medication;
}
