/// On-hand inventory for a medication pack: how much is left versus the
/// pack's full size, plus the low-stock warning threshold.
///
/// Pure Dart value object of the medication domain model — no Flutter, drift,
/// or uuid imports (constitution §2.1). See [PackStock].
library;

import 'package:freezed_annotation/freezed_annotation.dart';

part 'pack_stock.freezed.dart';

/// Tracks remaining inventory of a medication relative to a full pack.
///
/// All quantities are expressed in whole dose-units (see `DoseUnit`).
/// Equality and `hashCode` are generated by freezed.
@freezed
abstract class PackStock with _$PackStock {
  /// Creates a [PackStock] snapshot.
  const factory PackStock({
    /// Units currently left in the pack.
    required int remaining,

    /// Units in a full pack (the size a refill restores [remaining] to).
    required int total,

    /// Low-stock threshold: when [remaining] drops to or below this value,
    /// the user should be warned to refill.
    required int warnAt,
  }) = _PackStock;
}
