/// The recurring intake plan for a medication: a [frequency] paired with the
/// per-occurrence [Schedule.slots].
///
/// Pure Dart value object of the medication domain model — no Flutter, drift,
/// or uuid imports (constitution §2.1). See [Schedule].
library;

import 'package:freezed_annotation/freezed_annotation.dart';

import 'schedule_frequency.dart';
import 'time_slot.dart';

part 'schedule.freezed.dart';

/// When and how often a medication is taken within its recurrence window.
///
/// [frequency] describes the recurrence cadence (currently always
/// [ScheduleFrequency.daily]); [slots] lists the times of day at which a dose is
/// due on each occurrence. Equality and `hashCode` are generated by freezed.
@freezed
abstract class Schedule with _$Schedule {
  /// Creates a [Schedule] with the given [frequency] and [slots].
  const factory Schedule({
    /// How often the [slots] recur. Defaults to [ScheduleFrequency.daily].
    @Default(ScheduleFrequency.daily) ScheduleFrequency frequency,

    /// The times of day at which a dose is due on each occurrence.
    required List<TimeSlot> slots,
  }) = _Schedule;
}
