/// A scheduled time of day at which a medication is to be taken, optionally
/// overriding the medication's default [Dosage] for this slot.
///
/// Pure Dart value object of the medication domain model — no Flutter, drift,
/// or uuid imports (constitution §2.1). See [TimeSlot].
library;

import 'package:freezed_annotation/freezed_annotation.dart';

import '../value_objects/time_slot_id.dart';
import 'dosage.dart';

part 'time_slot.freezed.dart';

/// A single point in a medication's daily schedule.
///
/// Identified by [id] and expressed as a [minuteOfDay]. An optional
/// [doseOverride] lets this slot take a different [Dosage] than the
/// medication's default. Equality and `hashCode` are generated by freezed.
@freezed
abstract class TimeSlot with _$TimeSlot {
  /// Creates a [TimeSlot] at [minuteOfDay] identified by [id].
  const factory TimeSlot({
    /// Stable identifier for this slot.
    required TimeSlotId id,

    /// Local wall-clock minute of the day, in the range `0..1439`
    /// (`0` = 00:00, `1439` = 23:59). This is a wall-clock value, not a
    /// UTC offset — it intentionally carries no timezone information.
    required int minuteOfDay,

    /// Per-slot dose that replaces the medication's default dose for this
    /// slot when non-null; `null` means "use the medication's default dose".
    Dosage? doseOverride,
  }) = _TimeSlot;
}
