/// Pure-Dart unit tests for [AppSettings].
///
/// AC-16: covers [AppSettings.copyWith] (generated by freezed) and value
/// equality. No Flutter binding required — [AppSettings] and [AppThemeMode]
/// are pure Dart domain types per constitution §2.1.
library;

import 'package:dosly/features/settings/domain/entities/app_language.dart';
import 'package:dosly/features/settings/domain/entities/app_settings.dart';
import 'package:dosly/features/settings/domain/entities/app_theme_mode.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('AppSettings.copyWith', () {
    test('all-null copyWith() returns an equal instance (preserves all fields)',
        () {
      const original = AppSettings(
        useSystemTheme: false,
        manualThemeMode: AppThemeMode.dark,
        useSystemLanguage: false,
        manualLanguage: AppLanguage.uk,
      );

      final copy = original.copyWith();

      expect(copy, equals(original));
    });

    test('copyWith(useSystemTheme: false) replaces only useSystemTheme', () {
      const original = AppSettings();

      final copy = original.copyWith(useSystemTheme: false);

      expect(copy.useSystemTheme, isFalse);
      // All other fields stay at their defaults.
      expect(copy.manualThemeMode, AppThemeMode.light);
      expect(copy.useSystemLanguage, isTrue);
      expect(copy.manualLanguage, AppLanguage.en);
    });

    test('copyWith(manualThemeMode: dark) replaces only manualThemeMode', () {
      const original = AppSettings();

      final copy = original.copyWith(manualThemeMode: AppThemeMode.dark);

      expect(copy.manualThemeMode, AppThemeMode.dark);
      // All other fields stay at their defaults.
      expect(copy.useSystemTheme, isTrue);
      expect(copy.useSystemLanguage, isTrue);
      expect(copy.manualLanguage, AppLanguage.en);
    });

    test('copyWith(useSystemLanguage: false) replaces only useSystemLanguage',
        () {
      const original = AppSettings();

      final copy = original.copyWith(useSystemLanguage: false);

      expect(copy.useSystemLanguage, isFalse);
      // All other fields stay at their defaults.
      expect(copy.useSystemTheme, isTrue);
      expect(copy.manualThemeMode, AppThemeMode.light);
      expect(copy.manualLanguage, AppLanguage.en);
    });

    test('copyWith(manualLanguage: uk) replaces only manualLanguage', () {
      const original = AppSettings();

      final copy = original.copyWith(manualLanguage: AppLanguage.uk);

      expect(copy.manualLanguage, AppLanguage.uk);
      // All other fields stay at their defaults.
      expect(copy.useSystemTheme, isTrue);
      expect(copy.manualThemeMode, AppThemeMode.light);
      expect(copy.useSystemLanguage, isTrue);
    });
  });

  group('AppSettings equality', () {
    test('two AppSettings() instances with default values are equal', () {
      const a = AppSettings();
      const b = AppSettings();

      expect(a, equals(b));
    });

    test('AppSettings(useSystemTheme: false) is not equal to AppSettings()',
        () {
      const a = AppSettings(useSystemTheme: false);
      const b = AppSettings();

      expect(a, isNot(equals(b)));
    });
  });
}
