/// Hand-coded Material 3 color schemes for the dosly app.
///
/// Source of truth: `dosly_m3_template.html`, generated by the Material
/// Theme Builder (https://material-foundation.github.io/material-theme-builder/)
/// using the seed color `#4CAF50`.
///
/// This file is the single source of truth for every color literal in the
/// app. Widgets and themes must reference [lightColorScheme] / [darkColorScheme]
/// (or the derived [ThemeData]) rather than hard-coding colors.
///
/// `ColorScheme.fromSeed` is deliberately NOT used — see spec
/// `specs/001-m3-theme` AC-1. All values below are hand-coded literals so the
/// app exactly reproduces the designer-approved palette.
library;

import 'package:flutter/material.dart';

/// Light Material 3 color scheme.
///
/// Hand-coded from `dosly_m3_template.html` (Theme Builder seed: `#4CAF50`).
/// This is the single source of truth for every color literal in the app.
/// Do not use `ColorScheme.fromSeed` — see spec 001-m3-theme AC-1.
const ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,

  // Primary
  primary: Color(0xFF2E7D32),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFB7F0B1),
  onPrimaryContainer: Color(0xFF002204),

  // Secondary
  secondary: Color(0xFF52634F),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFD5E8CF),
  onSecondaryContainer: Color(0xFF101F0F),

  // Tertiary
  tertiary: Color(0xFF38656A),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFBCEBF0),
  onTertiaryContainer: Color(0xFF002023),

  // Error
  error: Color(0xFFBA1A1A),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF410002),

  // Surface
  surface: Color(0xFFF6FBF3),
  onSurface: Color(0xFF191C18),
  onSurfaceVariant: Color(0xFF404942),

  // Surface containers
  surfaceContainerLowest: Color(0xFFFFFFFF),
  surfaceContainerLow: Color(0xFFF0F5ED),
  surfaceContainer: Color(0xFFEAF0E7),
  surfaceContainerHigh: Color(0xFFE4EAE1),
  surfaceContainerHighest: Color(0xFFDFE4DC),
  // surfaceBright/Dim are NOT in the HTML source; derived from adjacent
  // container tones to preserve M3 semantics. See specs/001-m3-theme/research.md.
  surfaceBright: Color(0xFFF0F5ED),
  surfaceDim: Color(0xFFDFE4DC),

  // Outline
  outline: Color(0xFF70796E),
  outlineVariant: Color(0xFFC0C9BB),

  // Inverse
  inverseSurface: Color(0xFF2E312D),
  onInverseSurface: Color(0xFFEFF2EC),
  inversePrimary: Color(0xFF8BD988),

  // Misc
  surfaceTint: Color(0xFF2E7D32),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
);

/// Dark Material 3 color scheme.
///
/// Hand-coded from `dosly_m3_template.html` (Theme Builder seed: `#4CAF50`).
const ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,

  // Primary
  primary: Color(0xFF8BD988),
  onPrimary: Color(0xFF003A02),
  primaryContainer: Color(0xFF0A5210),
  onPrimaryContainer: Color(0xFFA6F5A2),

  // Secondary
  secondary: Color(0xFFB9CCAF),
  onSecondary: Color(0xFF253422),
  secondaryContainer: Color(0xFF3B4B37),
  onSecondaryContainer: Color(0xFFD5E8CF),

  // Tertiary
  tertiary: Color(0xFFA0CFD5),
  onTertiary: Color(0xFF00363B),
  tertiaryContainer: Color(0xFF1F4D52),
  onTertiaryContainer: Color(0xFFBCEBF0),

  // Error
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF690005),
  errorContainer: Color(0xFF93000A),
  onErrorContainer: Color(0xFFFFDAD6),

  // Surface
  surface: Color(0xFF101410),
  onSurface: Color(0xFFDFE4DC),
  onSurfaceVariant: Color(0xFFBFC9BB),

  // Surface containers
  surfaceContainerLowest: Color(0xFF0B0F0B),
  surfaceContainerLow: Color(0xFF191C18),
  surfaceContainer: Color(0xFF1D211C),
  surfaceContainerHigh: Color(0xFF272B26),
  surfaceContainerHighest: Color(0xFF323631),
  // surfaceBright/Dim are NOT in the HTML source; derived from adjacent
  // container tones to preserve M3 semantics. See specs/001-m3-theme/research.md.
  surfaceBright: Color(0xFF272B26),
  surfaceDim: Color(0xFF0B0F0B),

  // Outline
  outline: Color(0xFF8A9388),
  outlineVariant: Color(0xFF404942),

  // Inverse
  inverseSurface: Color(0xFFDFE4DC),
  onInverseSurface: Color(0xFF2E312D),
  inversePrimary: Color(0xFF1B6B1D),

  // Misc
  surfaceTint: Color(0xFF8BD988),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
);
