/// Cycle-day progress of a bounded or cyclic medication course: which day of
/// the active window the user is on, out of how many, and the current phase.
///
/// Pure Dart value object of the medication domain model — no Flutter, drift,
/// or uuid imports (constitution §2.1). All date math lives in
/// [CourseProgress.resolve]. See [CourseProgress].
library;

import 'package:freezed_annotation/freezed_annotation.dart';

import '../entities/course_phase.dart';
import '../entities/medication_type.dart';

part 'course_progress.freezed.dart';

/// Reduces [d] to its LOCAL calendar date (year/month/day), anchored to UTC so
/// the time-of-day component is discarded and every per-day span is exactly 24h.
///
/// Stored start dates are UTC with drift's local flag; comparing local calendar
/// dates (rather than raw instants) keeps the day boundary stable across
/// intraday time, avoiding the instant-equality trap. The returned value uses
/// the LOCAL year/month/day but constructs them as a UTC midnight: UTC has no
/// DST, so `_localDate(a).difference(_localDate(b)).inDays` counts whole
/// calendar days without DST drift. A local-midnight constructor would make a
/// span crossing a spring-forward boundary only `N*24h - 1h`, which `.inDays`
/// would truncate to `N - 1` (an off-by-one in the day counter).
DateTime _localDate(DateTime d) {
  final DateTime local = d.toLocal();
  return DateTime.utc(local.year, local.month, local.day);
}

/// Computed cycle-day progress of a [CourseType] medication at a given instant.
///
/// This is a COMPUTED value, never stored. [currentDay] is the 1-based day
/// within the active window (clamped so it never reports day 0 or a value past
/// [totalDays]); [totalDays] is the window length in days; [phase] indicates
/// whether the medication is in an active window or a paused gap. Equality and
/// `hashCode` are generated by freezed.
@freezed
abstract class CourseProgress with _$CourseProgress {
  /// Creates a [CourseProgress] snapshot.
  const factory CourseProgress({
    /// 1-based day within the current active window (never `0`, never above
    /// [totalDays]).
    required int currentDay,

    /// Number of active intake days in a single course window.
    required int totalDays,

    /// Whether the medication is currently in an active window or a paused gap.
    required CoursePhase phase,
  }) = _CourseProgress;

  /// Derives the [CourseProgress] for [course] as of [now].
  ///
  /// Compares LOCAL calendar dates: `daysSinceStart` is the number of whole
  /// days between the local start date and the local date of [now] (`0` on the
  /// start day).
  ///
  /// * Non-cyclic course (`pauseDays == 0`): always in [CoursePhase.activeWindow];
  ///   [currentDay] is `daysSinceStart + 1` clamped to [totalDays].
  /// * Cyclic course (`pauseDays > 0`): the cycle length is
  ///   `durationDays + pauseDays`. Within the active portion of the cycle the
  ///   phase is [CoursePhase.activeWindow] and [currentDay] tracks the day in
  ///   the window; during the gap the phase is [CoursePhase.paused] and
  ///   [currentDay] is pinned to [totalDays].
  /// * Future-dated start (`daysSinceStart < 0`): treated as
  ///   [CoursePhase.activeWindow] on day `1`.
  static CourseProgress resolve({
    required CourseType course,
    required DateTime now,
  }) {
    final int daysSinceStart =
        _localDate(now).difference(_localDate(course.startDate)).inDays;

    if (daysSinceStart < 0) {
      // Future-dated start: anchor to the first day of the active window.
      return CourseProgress(
        currentDay: 1,
        totalDays: course.durationDays,
        phase: CoursePhase.activeWindow,
      );
    }

    if (course.pauseDays == 0) {
      // Non-cyclic: a single bounded window, clamped at its final day.
      final int currentDay = daysSinceStart + 1 <= course.durationDays
          ? daysSinceStart + 1
          : course.durationDays;
      return CourseProgress(
        currentDay: currentDay,
        totalDays: course.durationDays,
        phase: CoursePhase.activeWindow,
      );
    }

    // Cyclic: alternating active windows and pause gaps. cycleLen is always
    // >= durationDays + 1 here (pauseDays > 0), so the modulo never divides by
    // zero.
    final int cycleLen = course.durationDays + course.pauseDays;
    final int posInCycle = daysSinceStart % cycleLen;
    if (posInCycle < course.durationDays) {
      return CourseProgress(
        currentDay: posInCycle + 1,
        totalDays: course.durationDays,
        phase: CoursePhase.activeWindow,
      );
    }
    return CourseProgress(
      currentDay: course.durationDays,
      totalDays: course.durationDays,
      phase: CoursePhase.paused,
    );
  }
}
