/// Typed identifier for a medication intake.
///
/// Pure Dart value object of the medication domain model — no Flutter, drift,
/// or uuid imports (constitution §2.1). See [IntakeId].
library;

import 'package:freezed_annotation/freezed_annotation.dart';

part 'intake_id.freezed.dart';

/// Strongly-typed identifier for a medication intake.
///
/// Wraps a single [value] string so an intake ID can never be confused
/// with another entity's ID at a call site (constitution §"Domain IDs are
/// typed value objects"). Equality and `hashCode` are generated by freezed.
///
/// There is intentionally NO `generate()` factory here: identifiers are
/// produced by an injected `IdGenerator` abstraction, keeping this value
/// object free of any `uuid`/randomness dependency.
@freezed
abstract class IntakeId with _$IntakeId {
  /// Wraps an existing identifier [value].
  const factory IntakeId(String value) = _IntakeId;
}
