/// Typed identifier for a medication.
///
/// Pure Dart value object of the medication domain model — no Flutter, drift,
/// or uuid imports (constitution §2.1). See [MedicationId].
library;

import 'package:freezed_annotation/freezed_annotation.dart';

part 'medication_id.freezed.dart';

/// Strongly-typed identifier for a medication.
///
/// Wraps a single [value] string so a medication ID can never be confused
/// with another entity's ID at a call site (constitution §"Domain IDs are
/// typed value objects"). Equality and `hashCode` are generated by freezed.
///
/// There is intentionally NO `generate()` factory here: identifiers are
/// produced by an injected `IdGenerator` abstraction, keeping this value
/// object free of any `uuid`/randomness dependency.
@freezed
abstract class MedicationId with _$MedicationId {
  /// Wraps an existing identifier [value].
  const factory MedicationId(String value) = _MedicationId;
}
