/// Typed identifier for a schedule time slot.
///
/// Pure Dart value object of the medication domain model — no Flutter, drift,
/// or uuid imports (constitution §2.1). See [TimeSlotId].
library;

import 'package:freezed_annotation/freezed_annotation.dart';

part 'time_slot_id.freezed.dart';

/// Strongly-typed identifier for a schedule time slot.
///
/// Wraps a single [value] string so a time-slot ID can never be confused
/// with another entity's ID at a call site (constitution §"Domain IDs are
/// typed value objects"). Equality and `hashCode` are generated by freezed.
///
/// There is intentionally NO `generate()` factory here: identifiers are
/// produced by an injected `IdGenerator` abstraction, keeping this value
/// object free of any `uuid`/randomness dependency.
@freezed
abstract class TimeSlotId with _$TimeSlotId {
  /// Wraps an existing identifier [value].
  const factory TimeSlotId(String value) = _TimeSlotId;
}
